line_length: 
 - 500 # warning
 - 800 # error

disabled_rules:
 - force_cast
 - force_try
 - identifier_name
 - opening_brace
 - trailing_whitespace
 - void_return
 - vertical_whitespace
 - private_over_fileprivate
 - comma
 - colon
 - switch_case_alignment 
 - trailing_semicolon
excluded:
 - Mini Challenge IIITests
 - Mini Challenge IIIUITests

