os: osx
language: objective-c
osx_image: xcode10.2
script:
  - set -o pipefail && xcodebuild build -project Mini Challenge III.xcodeproj -scheme Mini Challenge III -sdk iphonesimulator12.1 -destination 'name=iPhone 6,OS=12.1' ONLY_ACTIVE_ARCH=NO | xcpretty
